-- Supabase PostgreSQL Schema for GreenHeart Golf

-- Users table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    plan TEXT DEFAULT 'monthly' CHECK (plan IN ('monthly', 'yearly')),
    giving_pct INT DEFAULT 10,
    charity_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Charities table
CREATE TABLE IF NOT EXISTS public.charities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    supporters_count INT DEFAULT 0,
    raised_amount DECIMAL(10,2) DEFAULT 0.00,
    description TEXT,
    logo_url TEXT
);

-- Scores table
CREATE TABLE IF NOT EXISTS public.scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    score INT NOT NULL,
    course_name TEXT,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Draws table
CREATE TABLE IF NOT EXISTS public.draws (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_date DATE NOT NULL,
    winning_numbers TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'published'))
);

-- Winners table
CREATE TABLE IF NOT EXISTS public.winners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    draw_id BIGINT NOT NULL REFERENCES public.draws(id) ON DELETE CASCADE,
    match_count INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    proof_image TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'paid'))
);

-- Insert initial charities
INSERT INTO public.charities (name, category, supporters_count, raised_amount, description) VALUES 
('Macmillan Cancer Support', 'health', 840, 120000.00, 'Providing physical, financial and emotional support to help people live life as fully as they can.'),
('NSPCC', 'children', 620, 85000.00, 'Leading children''s charity fighting to end child abuse in the UK and Channel Islands.'),
('RSPCA', 'animals', 510, 64000.00, 'The oldest animal welfare charity in the world, rescuing, rehabilitating and rehoming animals.'),
('British Heart Foundation', 'health', 480, 56000.00, 'Funding world-class research to find cures and treatments for heart and circulatory diseases.'),
('Age UK', 'elderly', 390, 42000.00, 'The leading charity for older people, providing companionship, advice and support.'),
('Cancer Research UK', 'health', 960, 150000.00, 'Funding scientists, doctors and nurses to help beat cancer sooner.');
